// render-summary.mjs — the packet's HTML summary, rendered FROM the bank.
//
// WHY IT EXISTS. summary.html was hand-written and drifted: 11,402 bytes describing an 18-question
// bank, still on disk after the bank became 20 questions in 4 chunks, naming NONE of the four chunk
// titles it claimed to summarise. It is bullet 4 of the original ask, and packet-gate fails it on
// LP-02 and LP-03 for exactly that — a published view that is not generated from the store.
//
// The control condition sat in the same directory the whole time. NOTEBOOKLM-PACK.md renders from
// authority-map.json and byte-compares with --check, and it is the one artifact in this packet that
// cannot drift. The difference between the two was never care; it was a renderer.
//
// WHAT IT DELIBERATELY DOES NOT SHOW. Ideals are withheld. The summary is a map of the material for
// someone deciding whether to work through it, and `drill` grades against an ideal frozen before the
// attempt — publishing them in a browsable page hands the learner the answer key and quietly converts
// every later attempt from recall into recognition.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const BANK = path.join(HERE, 'resources', 'competency-progress.json');
export const MAP = path.join(HERE, 'packets/agent-harness-l1-l2/notebooklm/authority-map.json');
export const OUT = path.join(HERE, 'packets/agent-harness-l1-l2/summary.html');
export const COMPETENCY = 'agent-harness-l1-l2';

export const load = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));

/* HTML-escaped, because question prompts contain `<`, `>` and quotes and a summary that renders them
   as markup is a summary that silently changes what the bank says. */
const esc = (s) => String(s ?? '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const RUNGS = { 1: 'name it', 2: 'apply it', 3: 'trace the mechanism', 4: 'decide under conflict' };

export function render({ bank = load(BANK), map = load(MAP) } = {}) {
  const c = (bank.competencies ?? []).find((x) => x.id === COMPETENCY);
  if (!c) throw new Error(`${COMPETENCY} not in the bank`);
  const qs = c.questions ?? [];
  const sources = Object.entries(map.sources ?? {}).filter(([k]) => !k.startsWith('$'));
  const tier = (t) => qs.filter((q) => q.case?.tier === t).length;
  const sourcing = (s) => qs.filter((q) => q.sourcing === s).length;

  const L = [];
  const P = (s = '') => L.push(s);
  P('<!-- GENERATED by render-summary.mjs from resources/competency-progress.json and');
  P('     packets/agent-harness-l1-l2/notebooklm/authority-map.json.');
  P('     Do not hand-edit: `node render-summary.mjs --check` byte-compares and exits non-zero. -->');
  P('<meta charset="utf-8">');
  P(`<title>${esc(c.title ?? COMPETENCY)}</title>`);
  P('<style>');
  P('  :root{--ink:#16181d;--dim:#5a6270;--line:#e2e5ea;--bg:#fff;--accent:#1f4fd8}');
  P('  @media(prefers-color-scheme:dark){:root{--ink:#e8eaee;--dim:#98a1b0;--line:#2b2f38;--bg:#14161a;--accent:#7aa2ff}}');
  P('  body{background:var(--bg);color:var(--ink);font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;');
  P('       max-width:52rem;margin:0 auto;padding:2.5rem 1.25rem}');
  P('  h1{font-size:1.6rem;margin:0 0 .25rem}h2{font-size:1.1rem;margin:2.25rem 0 .5rem;border-bottom:1px solid var(--line);padding-bottom:.3rem}');
  P('  .sub{color:var(--dim);margin:0 0 1.5rem}');
  P('  table{border-collapse:collapse;width:100%;margin:.5rem 0 1rem;font-size:.94rem}');
  P('  th,td{text-align:left;padding:.45rem .6rem;border-bottom:1px solid var(--line);vertical-align:top}');
  P('  th{color:var(--dim);font-weight:600;font-size:.82rem;text-transform:uppercase;letter-spacing:.03em}');
  P('  .wrap{overflow-x:auto}code{background:color-mix(in srgb,var(--ink) 8%,transparent);padding:.1rem .3rem;border-radius:3px;font-size:.9em}');
  P('  .tag{display:inline-block;font-size:.75rem;padding:.1rem .4rem;border:1px solid var(--line);border-radius:3px;color:var(--dim)}');
  P('  a{color:var(--accent)}');
  P('</style>');
  P(`<h1>${esc(c.title ?? COMPETENCY)}</h1>`);
  P(`<p class="sub">${qs.length} questions across ${(c.parts ?? []).length} chunks · `
    + `${sources.length} sources · taught_at ${c.taught_at ? esc(c.taught_at) : '<em>not yet delivered</em>'}</p>`);

  P('<h2>What this teaches, in order</h2>');
  P('<div class="wrap"><table><tr><th>Chunk</th><th>Questions</th><th>Demand</th></tr>');
  (c.parts ?? []).forEach((title, i) => {
    const inChunk = qs.filter((q) => q.chunk === i + 1);
    const rungs = [...new Set(inChunk.map((q) => q.rung))].sort().map((r) => RUNGS[r] ?? r).join(' → ');
    P(`<tr><td><strong>${esc(title)}</strong></td><td>${inChunk.length}</td><td>${esc(rungs)}</td></tr>`);
  });
  P('</table></div>');

  P('<h2>The competency cases</h2>');
  P(`<p class="sub">Tier S means a source documents a real situation — ${tier('S')} of ${qs.length}. `
    + `Tier A is constructed and says so — ${tier('A')}.</p>`);
  P('<div class="wrap"><table><tr><th>Decision situation</th><th>Heuristic</th><th>Tier</th></tr>');
  for (const q of qs) {
    const k = q.case ?? {};
    P(`<tr><td>${esc(k.decision_situation)}</td><td>${esc(k.heuristic)}</td>`
      + `<td><span class="tag">${esc(k.tier)}</span></td></tr>`);
  }
  P('</table></div>');

  P('<h2>Where the claims come from</h2>');
  P(`<p class="sub">${sourcing('supported')} supported by a source · ${sourcing('analogy')} transferred by analogy · `
    + `${sourcing('unsourced')} the packet's own claim, marked as such.</p>`);
  P('<div class="wrap"><table><tr><th>Source</th><th>Read</th><th>Why this one</th></tr>');
  for (const [, s] of sources) {
    P(`<tr><td>${esc(s.title)}${s.url ? ` — <a href="${esc(s.url)}">link</a>` : ''}</td>`
      + `<td>${s.verified ? esc(s.verified.at) : '<em>not opened</em>'}</td>`
      + `<td>${esc(s.ranking_criterion)}</td></tr>`);
  }
  P('</table></div>');

  P('<h2>How to run it</h2>');
  P('<p>Open a Claude Code session on this directory, then:</p>');
  P('<table><tr><td><code>learn agent-harness-l1-l2</code></td><td>teaches a chunk, then asks</td></tr>');
  P('<tr><td><code>drill me</code></td><td>asks from the bank, grades against a frozen ideal</td></tr>');
  P('<tr><td><code>/icp-advisor</code></td><td>answers as ICP1 and ICP2, and names the inversion</td></tr>');
  P('<tr><td><code>node progress-store.mjs</code></td><td>the learning curve, or UNEVALUABLE with a reason</td></tr></table>');
  P('<p class="sub">Ideals are deliberately not published here — printing the answer key turns every '
    + 'later attempt from recall into recognition.</p>');
  return L.join('\n') + '\n';
}

function main(argv) {
  const text = render();
  if (!argv.includes('--check')) {
    fs.writeFileSync(OUT, text);
    console.log(`  wrote ${path.relative(HERE, OUT)} (${text.length} bytes)`);
    return 0;
  }
  let disk;
  try { disk = fs.readFileSync(OUT, 'utf8'); }
  catch { console.error('  REFUSED: summary.html absent. Run without --check.'); return 1; }
  if (disk === text) { console.log('  summary.html matches the bank.'); return 0; }
  console.error('  REFUSED: summary.html is not what the bank renders — hand-edited, or the bank moved.');
  return 1;
}
if (import.meta.url === `file://${process.argv[1]}`) process.exit(main(process.argv.slice(2)));
